### ISSUE TITLE
Folders/files with settings

### ISSUE THREAD

**Issue by nix155** [cagnulein/qdomyos-zwift#2865]
When running in Docker, settings are not saved after exiting. Which folders/files are used to store the settings (so they can be mapped from the host)?

**Comment by cagnulein** [comment]
the directory .config/ and subfolders in your home
debug log and other files are instead in the same qdomyoszwift binary folder

**Comment by cagnulein** [comment]
it should be

~/.config/qdomyoszwift/qdomyoszwift.conf

I never used qz in a docker (the docker file is from a user). So you can try to investigate this and in case let's do a PR :)

that folder exist on linux usually without docker

let me know

**Comment by nix155** [comment]
Wow, thank you! I found it!
docker exec -it qdomyos-zwift cat /root/.config/'Roberto Viola'/qDomyos-Zwift.conf
Here’s the Dockerfile I wrote for building:

```
FROM ubuntu:latest

# Install essential dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y \
    && apt install -y \
        git \
        qtquickcontrols2-5-dev \
        libqt5bluetooth5 \
        libqt5widgets5 \
        libqt5positioning5 \
        libqt5xml5 \
        qtconnectivity5-dev \
        qtbase5-private-dev \
        qtpositioning5-dev \
        libqt5charts5-dev \
        libqt5charts5 \
        qt5-assistant \
        libqt5networkauth5-dev \
        libqt5websockets5-dev \
        qml-module* \
        libqt5texttospeech5-dev \
        libqt5texttospeech5 \
        libqt5location5-plugins \
        qtlocation5-dev \
        qtmultimedia5-dev \
        libqt5multimediawidgets5 \
        libqt5multimedia5-plugins \
        libqt5multimedia5 \
        g++ \
        make \
        bluez \
        dbus \
        xfce4 \
        tightvncserver \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove \
    && apt-get clean

# Clone the project and build it
WORKDIR /usr/local/src
RUN git clone --recursive https://github.com/cagnulein/qdomyos-zwift.git
WORKDIR /usr/local/src/qdomyos-zwift
RUN git submodule update --init src/smtpclient/ \
    && git submodule update --init src/qmdnsengine/ \
    && git submodule update --init tst/googletest/
WORKDIR /usr/local/src/qdomyos-zwift/src
RUN qmake qdomyos-zwift.pro \
    && make -j4

# Configure VNC
RUN mkdir -p /root/.vnc \
    && echo "password" | vncpasswd -f > /root/.vnc/passwd \
    && chmod 600 /root/.vnc/passwd

# Start VNC and the application
CMD tightvncserver && ./qdomyos-zwift

```
Here’s the docker-compose.yml

```
services:
  qdomyos-zwift:
    image: qdomyos-zwift-vnc
    container_name: qdomyos-zwift
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - USER=docker
    volumes:
      - /dev:/dev
      - /run/dbus:/run/dbus
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    restart: "no"
    command: bash -c "tightvncserver && ./qdomyos-zwift"

```
