### ISSUE TITLE
[BUG] Technogym Myrun treadmill connects, but shows no speed or distance in QZ running on Linux

### ISSUE THREAD

**Issue by dmccombs** [cagnulein/qdomyos-zwift#3253]
**Describe the bug**
I'm trying to get `qdomyos-zwift` working natvely on Linux. To test things out, I'm just trying to run it via its GUI for now, but will want to run it without a GUI eventually. It sees and seems to connect to my Technogym Myrun treadmill, but starting the treadmill doesn't show any speed or distance changes in the QZ UI. What am I missing?

**To Reproduce**
1. Run `sudo ./qdomyos-zwift`
2. Observe the QZ UI says "MyRun 19000126 found"
3. Start the treadmill via the treadmill itself, increase the speed a small amount
4. Observe the QZ UI does not show any change in speed, though is still showing connected to the treadmill

**Expected behavior**
QZ should show the speed, cadence, and distance of the treadmill while it's running.

**Screenshots**
![Image](https://github.com/user-attachments/assets/44bb4067-135e-4c9a-83be-975dabe111f5)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: Kernel 6.12.10

**Append a debug log**
Below are debug logs trying different varieties of options without success.

[debug-Thu_Feb_27_10_52_45_2025.log](https://github.com/user-attachments/files/19012999/debug-Thu_Feb_27_10_52_45_2025.log)
[debug-Thu_Feb_27_10_50_26_2025.log](https://github.com/user-attachments/files/19013001/debug-Thu_Feb_27_10_50_26_2025.log)
[debug-Thu_Feb_27_10_29_35_2025.log](https://github.com/user-attachments/files/19013000/debug-Thu_Feb_27_10_29_35_2025.log)
[debug-Thu_Feb_27_10_27_57_2025.log](https://github.com/user-attachments/files/19012998/debug-Thu_Feb_27_10_27_57_2025.log)

**Comment by cagnulein** [comment]
I guess it's a issue of the Bluetooth dongle.
Did you try another one? I always suggest bt400

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 feb 2025 alle 17:40 Dan McCombs ***@***.***>
ha scritto:

**Comment by dmccombs** [comment]
I haven't tried another Bluetooth dongle. I just ordered a bt400 and will have it tomorrow to try out. Thanks!

**Comment by cagnulein** [comment]
Ok let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 feb 2025 alle 17:52 Dan McCombs ***@***.***>
ha scritto:

**Comment by dmccombs** [comment]
Hmm, no, same issue with an ASUS BT400 dongle, it connects to the treadmill fine, but once the treadmill is moving it still shows a speed of 0.0 in QZ.

Here's the debug log with the new dongle: 

[debug-Fri_Feb_28_19_18_15_2025.log](https://github.com/user-attachments/files/19034498/debug-Fri_Feb_28_19_18_15_2025.log)

**Comment by cagnulein** [comment]
Is qz ok on your phone instead? Because if I saw correctly your treadmill is using Bluetooth 1.1 so I never play with this on Linux(bt400 gives me this information lucky for us)

**Comment by dmccombs** [comment]
Yes, running QZ on my Android phone with this treadmill works with default settings: 

![Image](https://github.com/user-attachments/assets/9b1ca763-61cf-4843-9e82-5de25e5d04ca)

Here's the debug log from it working on my phone: 

[debug-Sat_Mar_1_06_51_34_2025.log](https://github.com/user-attachments/files/19038748/debug-Sat_Mar_1_06_51_34_2025.log)

**Comment by dmccombs** [comment]
Thanks Roberto. Let me know if there's any other info I can provide or anything I can try that would help figure things out.

**Comment by dmccombs** [comment]
I've done some more testing this morning and have some more info that might be useful.

While I haven't fixed the treadmill issue, I did find a problem causing my Kickr Bike to not work and fixed that, so I'm including the info here to help other folks that come across this issue in the future.

I tried connecting my Wahoo Kickr Bike (v1) to QZ running on Linux via the BT400 dongle, and unlike the Technogym treadmill, it wasn't even seeing the device. I checked dmesg while unplugging/plugging in my dongle and noticed this message about a missing firmware patch:
```
[ 1412.472845] Bluetooth: hci0: BCM: chip id 63
[ 1412.474837] Bluetooth: hci0: BCM: features 0x07
[ 1412.491838] Bluetooth: hci0: BCM20702A
[ 1412.491842] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[ 1412.493876] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[ 1412.493878] Bluetooth: hci0: BCM: 'brcm/BCM20702A1-0b05-17cb.hcd'
[ 1412.493880] Bluetooth: hci0: BCM: 'brcm/BCM-0b05-17cb.hcd'
[ 1412.573992] Bluetooth: MGMT ver 1.23
```

I checked around and found that particular firmware patch, it's available either on [Github here](https://github.com/winterheart/broadcom-bt-firmware/blob/master/brcm/BCM20702A1-0b05-17cb.hcd) or for the Linux distribution I use, it's part of this [Archlinux user repository package](https://aur.archlinux.org/packages/broadcom-bt-firmware-git).

Once I installed that, the Kickr Bike connects and works as expected - it even relays the connection to Zwift running in Wine on the same machine via direct connect without issue. Too cool! There hasn't been a way to connect devices to Zwift running on Linux without running the phone companion app before.
![Image](https://github.com/user-attachments/assets/ec1ce9a6-7042-44aa-b529-566dc31aebd6)

The Technogym MyRun treadmill still connects, but doesn't show any speed info in QZ on Linux when it's moving. In case anything is different in the debug log after putting that BT firmware in place, here's a new debug log with the treadmill not working:

[debug-Sun_Mar_2_08_24_20_2025.log](https://github.com/user-attachments/files/19043209/debug-Sun_Mar_2_08_24_20_2025.log)

I tried with the `technogym_myrun_treadmill_experimental` setting both off and on to see if it made any difference, but it didn't show the speed in either case.

**Comment by cagnulein** [comment]
Thanks for the update, I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 mar 2025 alle 14:38 Dan McCombs ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
for sure this MUST be disabled

technogym_myrun_treadmill_experimental

also remove the treadmill from the ftms treadmill setting

let me know if it's better

**Comment by dmccombs** [comment]
With `technogym_myrun_treadmill_experimental` disabled and the FTMS dropdown set to `Disabled`, it's still connecting but not showing speed.

Is there a configuration file I can remove to reset QZ to all its default settings? I had tried turning a lot on and off when I was first having the problem, so it'd be nice to get back to all the defaults.

**Comment by dmccombs** [comment]
Here's the debug log after removing the configuration file and starting QZ without changing any settings aside from turning on the debug logging, still with the same problem:

[debug-Mon_Mar_3_07_51_44_2025.log](https://github.com/user-attachments/files/19053495/debug-Mon_Mar_3_07_51_44_2025.log)

> on linux should be on the /home/[user]/.config/qt and so on. you should find it there. you can safely remove it and open qz again

At first I was looking in my user home directory and not finding anything, then realized QZ runs as root - it ended up being at `/root/.config/Roberto Viola/qDomyos-Zwift.conf`

**Comment by cagnulein** [comment]
good call!

```
Mon Mar 3 07:51:50 2025 1741006310429 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString&) "technogymmyruntreadmill::errorUnknownRemoteDeviceErrorRemote device cannot be found"
Mon Mar 3 07:51:50 2025 1741006310430 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString&) "Cannot connect to remote device."
Mon Mar 3 07:51:50 2025 1741006310430 Debug:   QLowEnergyControllerPrivate setting state to QLowEnergyController::UnconnectedState
Mon Mar 3 07:51:50 2025 1741006310430 Debug: devices/technogymmyruntreadmill/technogymmyruntreadmill.cpp void technogymmyruntreadmill::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::UnconnectedState
Mon Mar 3 07:51:50 2025 1741006310430 Debug: devices/technogymmyruntreadmill/technogymmyruntreadmill.cpp void technogymmyruntreadmill::controllerStateChanged(QLowEnergyController::ControllerState) "trying to connect back again..."
Mon Mar 3 07:51:50 2025 1741006310489 Debug:   QLowEnergyControllerPrivateBluezDBus::connectToDevice()
Mon Mar 3 07:51:50 2025 1741006310490 Debug:   Cannot find targeted remote device. Re-running device discovery might help
Mon Mar 3 07:51:50 2025 1741006310490 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString&) "technogymmyruntreadmill::errorUnknownRemoteDeviceErrorRemote device cannot be found"
```

did you already try to reboot the PC?

**Comment by dmccombs** [comment]
I tried rebooting now and running it again, but still see those device cannot be found/cannot connect to remote device in the new debug log:

[debug-Mon_Mar_3_09_12_32_2025.log](https://github.com/user-attachments/files/19054538/debug-Mon_Mar_3_09_12_32_2025.log)

**Comment by cagnulein** [comment]
are you able to use bluetoothctl command on linux to connect and subscribe
to notifications to the treadmill?
I'm start thinking that there is some incompatibility between linux and
this treadmill

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 mar 2025 alle ore 15:16 Dan McCombs <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok that's the main reason. if this doesn't work means that the bluetooth layer on linux has some issues with it. i suggest to try to check on internet if there are any error about this

**Comment by dmccombs** [comment]
I'll see what I can find and report back here.

**Comment by dmccombs** [comment]
So, comparing the device info in `bluetoothctl` between my Kickr Bike (which works in QZ and can be connected to in `bluetoothctl`) and the Technogym MyRun treadmill and looking at the UUIDs listed, I notice that the Kickr Bike has `Generic Access Profile` and `Generic Attribute Profile` listed, which seem to map to GAP/GATT and BLE access, while the MyRun treadmill has `Serial Port` listed instead:

```
Device F8:21:61:6D:5D:8C (random)
        Name: KICKR BIKE B548
        Alias: KICKR BIKE B548
        Appearance: 0x0484 (1156)
        Paired: no
        Bonded: no
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Cycling Power             (00001818-0000-1000-8000-00805f9b34fb)
        UUID: User Data                 (0000181c-0000-1000-8000-00805f9b34fb)
        UUID: Fitness Machine           (00001826-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (a026ee01-0a7d-4ab3-97fa-f1500f9feb8b)
        UUID: Vendor specific           (a026ee0b-0a7d-4ab3-97fa-f1500f9feb8b)
        UUID: Vendor specific           (a026ee0d-0a7d-4ab3-97fa-f1500f9feb8b)
        AdvertisingFlags:
  06
```

```
Device 00:81:F9:05:C7:EA (public)
        Name: MyRun 19000126
        Alias: MyRun 19000126
        Class: 0x00240704 (2361092)
        Paired: no
        Bonded: no
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Vendor specific           (00000000-deca-fade-deca-deafdecacaff)
        UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Running Speed and Cadence (00001814-0000-1000-8000-00805f9b34fb)
        UUID: Fitness Machine           (00001826-0000-1000-8000-00805f9b34fb)
        ServiceData.00001826-0000-1000-8000-00805f9b34fb:
  01 01 00                                         ...
        AdvertisingFlags:
  12
```

Looking around some, connecting to a serial port over bluetooth is different in the `bluez` stack on Linux, you basically pair and trust the device in `bluetoothctl`, then use an `rfcomm` command (which is now deprecated) to bind it to a device that can then be opened. ([source](https://wiki.archlinux.org/title/Bluetooth#Bluetooth_serial)).

So, if this treadmill really is supposed to connect via serial, this weirdness with bluez might be causing problems. Even when I try it though, I don't know what baud to set it to or what to send to the treadmill, and it just exits with I/O errors.

Anyway, I have very little experience with any kind of development with Bluetooth devices, so I could be far off. Have you seen other fitness devices that need a serial connection if that's what's going on here? If so, I wonder if all of those won't work on Linux or would need some special handling to.
